name: Evening Report (5pm NY)

on:
  schedule:
    # 5pm ET = 21:00 UTC during EDT, 22:00 UTC during EST
    - cron: "0 21 * * 1-5"
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

# keep your existing concurrency group name if you like
concurrency:
  group: evening-report
  cancel-in-progress: true

jobs:
  gate:
    name: Gate (run only at 5pm New York or manual)
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        shell: bash
        run: |
          # Manual runs always proceed
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Check local New York time
          wd=$(TZ=America/New_York date +%u)  # 1=Mon .. 7=Sun
          hr=$(TZ=America/New_York date +%H)  # 00..23
          if [ "$wd" -ge 1 ] && [ "$wd" -le 5 ] && [ "$hr" = "17" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

  report:
    name: Build & publish evening report
    needs: gate
    if: ${{ needs.gate.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish report to docs (excluding gapups.html)
        run: |
          rsync -av --delete --exclude 'gapups.html' report/ docs/

      - name: Commit and push changes
        run: |
          BRANCH="${{ github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ || true
          git add history/*.json || true
          git commit -m "Evening report update $(date -u +%F)" || echo "No changes"
          git pull --rebase origin "$BRANCH" || true
          git push origin HEAD:"$BRANCH"
