name: Evening Report (5pm NY)

on:
  schedule:
    - cron: "*/10 * * * 1-5"  # UTC; gate to 17:00 America/New_York below
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: evening-report
  cancel-in-progress: true

jobs:
  report:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gate to 17:00 in America/New_York
        if: ${{ github.event_name == 'schedule' }}
        run: |
          NY_HOUR=$(TZ="America/New_York" date +%H)
          NY_MIN=$(TZ="America/New_York" date +%M)
          if [ "$NY_HOUR" != "17" ] || [ "$NY_MIN" != "00" ]; then
            echo "Not 17:00 New York time. Exiting."
            exit 0
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install yfinance beautifulsoup4 lxml jinja2 python-dotenv

      - name: Run dispatcher (skip gap-ups)
        env:
          SKIP_GAPUPS: "1"
        run: |
          python dispatcher.py

      - name: Publish report to docs (excluding gapups.html)
        run: |
          rsync -av --delete --exclude 'gapups.html' report/ docs/

      - name: Commit and push changes
        run: |
          BRANCH="${{ github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ || true
          git add history/*.json || true
          git commit -m "Evening report update $(date -u +%F)" || echo "No changes"
          git pull --rebase origin "$BRANCH" || true
          git push origin HEAD:"$BRANCH"
