name: Evening Report (5pm NY)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * 1-5"

concurrency:
  group: evening-report
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gate – only continue at 5pm in New York (manual runs always proceed)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          NY_HOUR=$(TZ="America/New_York" date +%H)
          if [ "$NY_HOUR" != "17" ]; then
            echo "Not 5pm in New York. Exiting."
            exit 0
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install yfinance beautifulsoup4 lxml jinja2 python-dotenv

      - name: Validate YAML
        run: |
          python -m pip install yamllint
          yamllint .github/workflows/*.yml

      - name: Run dispatcher (skip gap-ups)
        env:
          SKIP_GAPUPS: "1"
        run: |
          python dispatcher.py

      - name: Publish report to docs (excluding gapups.html)
        run: |
          rsync -av --delete --exclude 'gapups.html' report/ docs/

      - name: Commit and push changes
        run: |
          git config user.name "actions"
          git config user.email "actions@github.com"
          git add docs/ || true
          git add history/*.json || true
          git commit -m "Evening report update $(date -u +%F)" || echo "No changes"
          git push
