name: Update Report (5pm New York, Mon–Fri)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 1-5"
    - cron: "0 22 * * 1-5"

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Gate: run at 5pm NY on schedule; always run on manual"
        id: gate
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run_ok=true" >> $GITHUB_OUTPUT
          else
            hour=$(TZ="America/New_York" date +%H)
            if [ "$hour" = "17" ]; then
              echo "run_ok=true" >> $GITHUB_OUTPUT
            else
              echo "run_ok=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Checkout
        if: steps.gate.outputs.run_ok == 'true'
        uses: actions/checkout@v4

      - name: Set up Python
        if: steps.gate.outputs.run_ok == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        if: steps.gate.outputs.run_ok == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build report (runs dispatcher.py)
        if: steps.gate.outputs.run_ok == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5
          DEBUG: "0"
          PUBLIC: "1"    # set "0" if you want Prompt/Response shown publicly
        run: |
          python dispatcher.py
          cp -f report/overview.html report/index.html || true
          touch report/.nojekyll
          echo "::group::report dir listing"
          ls -la report
          echo "::endgroup::"

      - name: Mirror report/ to docs/
        if: steps.gate.outputs.run_ok == 'true'
        run: |
          rm -rf docs/*
          mkdir -p docs
          cp -r report/* docs/
          echo "::group::docs AFTER"
          ls -la docs
          echo "::endgroup::"

      - name: Commit & push changes
        if: steps.gate.outputs.run_ok == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto-update report ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
          git push
