name: Update Report (5pm, Mon–Fri)

on:
  schedule:
    - cron: '0 21 * * 1-5'   # 21:00 UTC; we also gate by NY time below
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # <-- mapped from Actions secrets
      LOCAL_TZ: America/New_York
      CONSOLIDATE_HISTORY: '1'
      DISABLE_SYNTH_HOLD: '1'
      USE_SCAN: '1'

    steps:
      - name: "Gate: only continue if it's 5pm in New York (manual runs always proceed)"
        id: gate
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run=yes" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          NY_HOUR=$(TZ=America/New_York date +%H)
          NY_DOW=$(TZ=America/New_York date +%u) # 1=Mon..7=Sun
          if [ "$NY_DOW" -ge 1 ] && [ "$NY_DOW" -le 5 ] && [ "$NY_HOUR" -eq 17 ]; then
            echo "run=yes" >> "$GITHUB_OUTPUT"
          else
            echo "run=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        if: steps.gate.outputs.run == 'yes'
        uses: actions/checkout@v4

      # Optional: quick sanity checks (won't print the secret value)
      - name: "Sanity: OPENAI_API_KEY visible to shell?""
        if: steps.gate.outputs.run == 'yes'
        run: |
          if [ -n "${OPENAI_API_KEY}" ]; then
            echo "OPENAI_API_KEY is set (length ≈ ${#OPENAI_API_KEY})"
          else
            echo "OPENAI_API_KEY is NOT set"
            exit 1
          fi

      - name: "Sanity: Python sees OPENAI_API_KEY?""
        if: steps.gate.outputs.run == 'yes'
        run: |
          python - << 'PY'
            import os, sys
            print("python sees OPENAI_API_KEY:", "yes" if os.getenv("OPENAI_API_KEY") else "no")
            sys.exit(0 if os.getenv("OPENAI_API_KEY") else 1)
            PY

      - name: Set up Python
        if: steps.gate.outputs.run == 'yes'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.gate.outputs.run == 'yes'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run dispatcher
        if: steps.gate.outputs.run == 'yes'
        run: python dispatcher.py

      - name: Publish report to docs/
        if: steps.gate.outputs.run == 'yes'
        shell: bash
        run: |
          mkdir -p docs
          if command -v rsync >/dev/null 2>&1; then
            rsync -av --delete report/ docs/
          else
            rm -rf docs/*
            cp -R report/* docs/
          fi
          touch docs/.nojekyll

      - name: Commit & push site + history
        if: steps.gate.outputs.run == 'yes'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add docs history report || true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto: report & history $(TZ=UTC date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
